#logging:
#  pattern:
#    console: "%d - %msg%n"
#  path: /var/log/tomcat/
#  file: /var/log/tomcat/sell.log
#  level:
#    com.panda.sell.LoggerTest : debug
#  level: debug
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost/springboot-wxorder?characterEncoding=utf-8&useSSL=false
  jackson:
    default-property-inclusion: non_null
  mvc:
      static-path-pattern: /**
  redis:
    host: 127.0.0.1
    port: 6379

server:
  servlet:
    context-path: /sell

wechat:
  mpAppId: wxe56e73d8f0c6c69b
  mpAppSecret: e1fc96b75176b172d863d61767a604cb
  openAppId: xxxx
  openAppSecret: xxxx
  mchId: 1409146202
  mchKey: c976503d34ca432c601361f969fd8d85
  keyPath: /xxx
  notifyUrl: xxx
  templateId:
    orderStatus: lCX_bEevbG2TcvdvJTeyBaEj3rhmM_1v3oAUWRqCJGk
projecturl:
  wechatMpAuthorize: http://192.168.1.6:8080
  wechatOpenAuthorize: http://192.168.1.6:8080
  sell: http://192.168.1.6:8080
logging:
  level:
    com.panda.dataobject.mapper: trace
mybatis:
  mapper-locations: classpath:mapper/*.xml  #classpath就表示resource目录